// flow-typed signature: 23066cdcd50d48f8bc08d507de3f2208
// flow-typed version: <<STUB>>/redux-undoredo_v2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-undoredo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-undoredo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-undoredo/dist/redux-undoredo' {
  declare module.exports: any;
}

declare module 'redux-undoredo/src/redux-undoredo' {
  declare module.exports: any;
}

declare module 'redux-undoredo/test/action-creators' {
  declare module.exports: any;
}

declare module 'redux-undoredo/test/reducers' {
  declare module.exports: any;
}

declare module 'redux-undoredo/test/redux-undoredo-test' {
  declare module.exports: any;
}

declare module 'redux-undoredo/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-undoredo/dist/redux-undoredo.js' {
  declare module.exports: $Exports<'redux-undoredo/dist/redux-undoredo'>;
}
declare module 'redux-undoredo/src/redux-undoredo.js' {
  declare module.exports: $Exports<'redux-undoredo/src/redux-undoredo'>;
}
declare module 'redux-undoredo/test/action-creators.js' {
  declare module.exports: $Exports<'redux-undoredo/test/action-creators'>;
}
declare module 'redux-undoredo/test/reducers.js' {
  declare module.exports: $Exports<'redux-undoredo/test/reducers'>;
}
declare module 'redux-undoredo/test/redux-undoredo-test.js' {
  declare module.exports: $Exports<'redux-undoredo/test/redux-undoredo-test'>;
}
declare module 'redux-undoredo/webpack.config.js' {
  declare module.exports: $Exports<'redux-undoredo/webpack.config'>;
}
